apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: sov-subgraph-watcher
  name: sov-subgraph-watcher
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sov-subgraph-watcher
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sov-subgraph-watcher
    spec:
      containers:
      - image: sovryn/sov-subgraph-watcher
        imagePullPolicy: Always
        name: sov-subgraph-watcher
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        envFrom:
        - secretRef:
            name: sov-subgraph-watcher
        - secretRef:
            name: sov-subgraph-watcher-secrets
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: regcred
