version: '3'

services:
  postgres:
    image: postgres:10.5-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sov-subgraph-watcher
    networks:
      - sovryn
    volumes:
      - ./.docker/dev/postgres:/data/db
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  sovryn:
    driver: bridge
    ipam:
      driver: default
